name: medfast
services:

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: medfast
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      SERVER_PORT: 5432
    ports:
      - "5432:5432"

  frontend:
    build: ./medfast-fe
    depends_on:
      - backend
    environment:
      API_HOST: "http://backend:8080"
      LOCAL_HOST: "http://localhost:3000"
    ports:
      - "3000:80"

  backend:
    build: ./medfast-be
    # image: healflowdev/medfast:latest
    depends_on:
      - postgresql
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/medfast
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: secret
      MAIL_PASSWORD: "pyne podv rskn cqof"
      SPRING_PROFILES_ACTIVE: dev  # Default profile; change to prod as needed
    # ports:
    #   - "8080:8080"

