app_name                = "medfast"
resource_group_name     = "medfast-rg-prod"
location                = "northeurope"
vm_username             = "azureadmin"
storage_account_name    = "medfasttfprod"
storage_container_name  = "tfstate"
container_registry_name = "medfastcr"