apiVersion: v1
kind: Service
metadata:
  name: medfast-frontend-service
spec:
  selector:
    app: medfast-frontend
  ports:
  - name: http
    protocol: TCP
    port: 80         # Expose port 80 on the service
    targetPort: 80   # Send traffic to port 80 on the pod

