export const SURNAME_SORT_KEY = 'SURNAME';
export const EMAIL_SORT_KEY = 'EMAIL';
export const SPECIALIZATION_SORT_KEY = 'SPECIALIZATION'
export const STATUS_SORT_KEY = 'STATUS';
export const STATUS_ACTIVE = 'ACTIVE';
export const STATUS_DEACTIVATED = 'DEACTIVATED';
export const STATUS_WAITING_FOR_CONFIRMATION = 'WAITING_FOR_CONFIRMATION';
export const STATUS_DELETED = 'DELETED'
