-- liquibase formatted sql

-- changeset David.Rabko:1_MED_210_Login
CREATE TABLE refresh_tokens
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token              VARCHAR(36)                              NOT NULL,
  user_id            BIGINT                                   NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT refresh_token_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE refresh_tokens;

-- changeset David.Rabko:2_MED_210_Login
CREATE TABLE verification_tokens
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token              VARCHAR(36)                              NOT NULL,
  user_id            BIGINT                                   NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT verification_token_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE verification_tokens;

-- changeset David.Rabko:3_MED_210_Login
CREATE TABLE roles
(
  name VARCHAR(30) NOT NULL,
  CONSTRAINT role_pkey PRIMARY KEY (name),
  UNIQUE (name)
);
-- rollback DROP TABLE roles;

-- changeset Katarzyna.Osowska:1_MED_265_Admin_console
CREATE TABLE user_statuses
(
  name VARCHAR(25) NOT NULL,
  CONSTRAINT user_statuses_pkey PRIMARY KEY (name),
  UNIQUE (name)
);
-- rollback DROP TABLE user_statuses;

-- changeset David.Rabko:4_MED_210_Login
CREATE TABLE users
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  enabled            BOOLEAN   DEFAULT FALSE,
  email              VARCHAR(50)                             NOT NULL UNIQUE,
  password           VARCHAR(255)                            NOT NULL,
  checkbox_terms_and_conditions   BOOLEAN                    DEFAULT FALSE,
  role               VARCHAR(30)                             NOT NULL,
  user_status        VARCHAR(25)                             NOT NULL,
  person_id          BIGINT                                  NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE users;

-- changeset David.Rabko:8_MED_210_Login
ALTER TABLE refresh_tokens
  ADD CONSTRAINT refresh_tokens_users__fk FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE refresh_tokens DROP CONSTRAINT refresh_tokens_users__fk;

-- changeset David.Rabko:9_MED_210_Login
ALTER TABLE verification_tokens
  ADD CONSTRAINT verification_tokens_users__fk FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE verification_tokens DROP CONSTRAINT verification_tokens_users__fk;

-- changeset David.Rabko:10_MED_210_Login
ALTER TABLE users
  ADD CONSTRAINT users_roles__fk FOREIGN KEY (role) REFERENCES roles (name) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE users DROP CONSTRAINT users_roles__fk;

-- changeset Katarzyna.Osowska:2_MED_265_Admin_console
ALTER TABLE users
  ADD CONSTRAINT user_status__fk FOREIGN KEY (user_status) REFERENCES user_statuses (name) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE users DROP CONSTRAINT user_status__fk;

-- changeset David.Rabko:11_MED_223_Reset_password
CREATE TABLE one_time_passwords
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token              VARCHAR(4)                               NOT NULL,
  user_id            BIGINT                                   NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT password_reset_token_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE password_reset_tokens;

-- changeset David.Rabko:12_MED_223_Reset_password
ALTER TABLE one_time_passwords
  ADD CONSTRAINT password_reset_tokens_users__fk FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE password_reset_tokens DROP CONSTRAINT password_reset_tokens_users__fk;

-- changeset Uladzislau.Lukashevich:12_MED_143_Location
CREATE TABLE locations
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  hospital_name      VARCHAR(50)                             NOT NULL,
  street_address     VARCHAR(50)                             NOT NULL,
  house              VARCHAR(20)                             NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT location_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE locations;

-- changeset Uladzislau.Lukashevich:13_MED_145_Patient
CREATE TABLE patients
(
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  address_id         BIGINT                                  NOT NULL,
  CONSTRAINT patient_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE patients;

-- changeset Uladzislau.Lukashevich:16_MED_142_Doctor
CREATE TABLE specializations
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  specialization     VARCHAR(50)                    UNIQUE   NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT specialization_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE specializations;

-- changeset Uladzislau.Lukashevich:17_MED_142_Doctor
CREATE TABLE doctors
(
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  license_number VARCHAR(100)                            NOT NULL,
  location_id    BIGINT                                  NOT NULL,
  CONSTRAINT doctor_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE doctors;

-- changeset Uladzislau.Lukashevich:18_MED_142_Doctor
CREATE TABLE doctors_specializations_bridge
(
  doctor_id          BIGINT NOT NULL,
  specializations_id BIGINT NOT NULL,
  CONSTRAINT doctors_specializations_bridge_pkey PRIMARY KEY (doctor_id, specializations_id)
);
-- rollback DROP TABLE doctors_specialization_bridge;

-- changeset Uladzislau.Lukashevich:19_MED_142_Doctor
ALTER TABLE doctors_specializations_bridge
  ADD CONSTRAINT doctors_specializations_bridge_doctors__fk FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE doctors_specializations_bridge DROP CONSTRAINT doctors_specializations_bridge_doctors__fk;

-- changeset Uladzislau.Lukashevich:20_MED_142_Doctor
ALTER TABLE doctors_specializations_bridge
  ADD CONSTRAINT doctors_specializations_bridge_specializations__fk FOREIGN KEY (specializations_id) REFERENCES specializations (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE doctors_specializations_bridge DROP CONSTRAINT doctors_specializations_bridge_specializations__fk;

-- changeset Uladzislau.Lukashevich:23_MED_144_Appointment
CREATE TABLE appointment_statuses
(
  status VARCHAR(25) NOT NULL,
  CONSTRAINT status_pkey PRIMARY KEY (status),
  UNIQUE (status)
);
-- rollback DROP TABLE appointment_statuses;

-- changeset Anton.Dybko:1_MED_113_Appointment
CREATE TABLE appointment_types
(
  type VARCHAR(10) PRIMARY KEY
);
-- rollback DROP TABLE appointment_types;

-- changeset Uladzislau.Lukashevich:24_MED_144_Appointment
CREATE TABLE consultation_appointments
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  doctor_id          BIGINT                                  NOT NULL,
  patient_id         BIGINT                                  NOT NULL,
  service_id         BIGINT                                  NOT NULL,
  date_from          TIMESTAMP                               NOT NULL,
  date_to            TIMESTAMP                               NOT NULL,
  location_id        BIGINT,
  type               VARCHAR(10)                             NOT NULL,
  appointment_status VARCHAR(30)                             NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT consultation_appointment_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE consultation_appointments;

-- changeset Anton.Dybko:2_MED_113_Appointment
ALTER TABLE consultation_appointments
  ADD CONSTRAINT consultation_appointments_appointment_types__fk FOREIGN KEY (type) REFERENCES appointment_types (type) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_appointment_types__fk;

-- changeset Uladzislau.Lukashevich:25_MED_144_Appointment
ALTER TABLE consultation_appointments
  ADD CONSTRAINT consultation_appointments_appointment_statuses__fk FOREIGN KEY (appointment_status) REFERENCES appointment_statuses (status) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_appointment_statuses__fk;

-- changeset Uladzislau.Lukashevich:26_MED_144_Appointment
ALTER TABLE consultation_appointments
  ADD CONSTRAINT consultation_appointments_doctors__fk FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_doctors__fk;

-- changeset Uladzislau.Lukashevich:27_MED_144_Appointment
ALTER TABLE consultation_appointments
  ADD CONSTRAINT consultation_appointments_patients__fk FOREIGN KEY (patient_id) REFERENCES patients (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_patients__fk;

-- changeset Uladzislau.Lukashevich:28_MED_144_Appointment
ALTER TABLE consultation_appointments
  ADD CONSTRAINT consultation_appointments_locations__fk FOREIGN KEY (location_id) REFERENCES locations (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_locations__fk;

-- changeset Anton.Dybko:3_MED_196_Recommendations_section
CREATE TABLE genders
(
  gender VARCHAR(10) PRIMARY KEY
);
-- rollback DROP TABLE genders;

-- changeset Uladzislau.Lukashevich:34_MED_140_Appointment_Endpoint
CREATE TABLE persons
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name               VARCHAR(50)                             NOT NULL,
  surname            VARCHAR(50)                             NOT NULL,
  birth_date         DATE                                    NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  sex                VARCHAR(10)                             NOT NULL,
  citizenship        VARCHAR(50),
  contact_info_id    BIGINT                                  NOT NULL,

  CONSTRAINT person_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE persons;

-- changeset Anton.Dybko:4_MED_196_Recommendations_section
ALTER TABLE persons
  ADD CONSTRAINT persons_genders__fk FOREIGN KEY (sex) REFERENCES genders (gender) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE persons DROP CONSTRAINT persons_genders__fk;

-- changeset Uladzislau.Lukashevich:35_MED_140_Appointment_Endpoint
ALTER TABLE users
  ADD CONSTRAINT users_persons__fk FOREIGN KEY (person_id) REFERENCES persons (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE users DROP CONSTRAINT users_persons__fk;

-- changeset Uladzislau.Lukashevich:36_MED_140_Appointment_Endpoint
ALTER TABLE patients
  ADD CONSTRAINT patients_persons__fk FOREIGN KEY (id) REFERENCES persons (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE patients DROP CONSTRAINT patients_persons__fk;

-- changeset Uladzislau.Lukashevich:37_MED_140_Appointment_Endpoint
ALTER TABLE doctors
  ADD CONSTRAINT doctors_persons__fk FOREIGN KEY (id) REFERENCES persons (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE doctors DROP CONSTRAINT doctors_persons__fk;

-- changeset Uladzislau.Lukashevich:38_MED_140_Appointment_Endpoint
ALTER TABLE doctors
  ADD CONSTRAINT doctors_locations__fk FOREIGN KEY (location_id) REFERENCES locations (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE doctors DROP CONSTRAINT doctors_location__fk;

-- changeset Katarzyna.Osowska:1_MED_107_Medical_Tests
CREATE TABLE tests
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY    NOT NULL,
    test                    VARCHAR(30)       UNIQUE                    NOT NULL,
    created_date            TIMESTAMP                                   DEFAULT CURRENT_TIMESTAMP,
    last_modified_date      TIMESTAMP                                   DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(50),
    last_modified_by        VARCHAR(50),
    CONSTRAINT test_pkey    PRIMARY KEY (id)
);
-- rollback DROP TABLE tests;

-- changeset Yana.Yeustratsyeva:1_MED_111_Time_Slots_For_Medical_Tests
ALTER TABLE tests
  ADD COLUMN duration BIGINT NOT NULL;
-- rollback ALTER TABLE tests DROP COLUMN duration;

-- changeset Yana.Yeustratsyeva:13_MED_274_Add_Test_Data_To_Data_Base
ALTER TABLE tests
  ALTER COLUMN test TYPE VARCHAR(100);
-- rollback ALTER TABLE tests ALTER COLUMN test TYPE VARCHAR(30);

-- changeset Katarzyna.Osowska:39_MED_146_Medical_Tests
CREATE TABLE test_appointments
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY    NOT NULL,
    date_time               TIMESTAMP                                   NOT NULL,
    test_id                 BIGINT                                      NOT NULL,
    location_id             BIGINT                                      NOT NULL,
    patient_id              BIGINT                                      NOT NULL,
    appointment_status      VARCHAR(30)                                 NOT NULL,
    created_date            TIMESTAMP                                   DEFAULT CURRENT_TIMESTAMP,
    last_modified_date      TIMESTAMP                                   DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(50),
    last_modified_by        VARCHAR(50),
    pdf_result              BYTEA,
    CONSTRAINT test_appointment_pkey    PRIMARY KEY (id)
);
-- rollback DROP TABLE test_appointments;

-- changeset Katarzyna.Osowska:4_MED_265_Admin_console
ALTER TABLE test_appointments
  ADD CONSTRAINT test_appointments_appointment_statuses__fk FOREIGN KEY (appointment_status) REFERENCES appointment_statuses (status) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE test_appointments DROP CONSTRAINT test_appointments_appointment_statuses__fk;

-- changeset Katarzyna.Osowska:40_MED_146_Medical_Tests
ALTER TABLE test_appointments
  ADD CONSTRAINT patients__fk FOREIGN KEY (patient_id) REFERENCES persons (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE test_appointments DROP CONSTRAINT patients__fk;

-- changeset Anton.Dybko:2_MED_107_Medical_Tests
ALTER TABLE test_appointments
    ADD CONSTRAINT locations__fk FOREIGN KEY (location_id) REFERENCES locations (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE test_appointments DROP CONSTRAINT locations__fk;

-- changeset Anton.Dybko:3_MED_107_Medical_Tests
ALTER TABLE test_appointments
    ADD CONSTRAINT tests__fk FOREIGN KEY (test_id) REFERENCES tests (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE test_appointments DROP CONSTRAINT tests__fk;

-- changeset Anton.Dybko:4_MED_107_Medical_Tests
ALTER TABLE test_appointments
  ADD CONSTRAINT appointment_statuses__fk FOREIGN KEY (appointment_status) REFERENCES appointment_statuses (status) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE test_appointments DROP CONSTRAINT appointment_statuses__fk;

-- changeset Anton.Dybko:5_MED_107_Medical_Tests
CREATE EXTENSION IF NOT EXISTS pg_trgm;
-- rollback DROP EXTENSION pg_trgm;

-- changeset Anton.Dybko:41_MED_228_Doctors_Registration
ALTER TABLE users
  ADD COLUMN password_expiration_date TIMESTAMP;
-- rollback ALTER TABLE users DROP COLUMN password_expiration_date

CREATE TABLE services
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  service            VARCHAR(50)      UNIQUE                 NOT NULL,
  duration           BIGINT                                  NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT service_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE services;

-- changeset Uladzislau.Lukashevich:45_MED_106_Services
CREATE TABLE specializations_services_bridge
(
  specialization_id BIGINT NOT NULL,
  service_id        BIGINT NOT NULL,
  CONSTRAINT specializations_services_bridge_pkey PRIMARY KEY (specialization_id, service_id)
);
-- rollback DROP TABLE doctors_specialization_bridge;

-- changeset Uladzislau.Lukashevich:46_MED_106_Services
ALTER TABLE specializations_services_bridge
  ADD CONSTRAINT specializations_services_bridge_specializations__fk FOREIGN KEY (specialization_id) REFERENCES specializations (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE specializations_services_bridge DROP CONSTRAINT specializations_services_bridge_specializations__fk;

-- changeset Uladzislau.Lukashevich:47_MED_106_Services
ALTER TABLE specializations_services_bridge
  ADD CONSTRAINT specializations_services_bridge_services__fk FOREIGN KEY (service_id) REFERENCES services (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE specializations_services_bridge DROP CONSTRAINT specializations_services_bridge_services__fk;

-- changeset Uladzislau.Lukashevich:48_MED_106_Services
ALTER TABLE consultation_appointments
  ADD CONSTRAINT  consultation_appointments_services__fk FOREIGN KEY (service_id) REFERENCES services(id) ON UPDATE RESTRICT ON DELETE RESTRICT ;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_services__fk;

-- changeset Katarzyna.Osowska:1_MED_163_user_info_management
CREATE TABLE contact_infos
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  phone              VARCHAR(11),

  CONSTRAINT contact_info_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE contact_infos;

-- changeset Katarzyna.Osowska:2_MED_163_user_info_management
CREATE TABLE addresses
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  street_address     VARCHAR(50),
  house              VARCHAR(20),
  apartment          VARCHAR(20),
  city               VARCHAR(50),
  state              VARCHAR(50),
  zip                VARCHAR(5),

  CONSTRAINT address_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE addresses;

-- changeset Katarzyna.Osowska:3_MED_163_user_info_management
ALTER TABLE patients
  ADD CONSTRAINT address__fk FOREIGN KEY (address_id) REFERENCES addresses (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE patients DROP CONSTRAINT address__fk;

-- changeset Katarzyna.Osowska:4_MED_163_user_info_management
ALTER TABLE persons
  ADD CONSTRAINT contact_info__fk FOREIGN KEY (contact_info_id) REFERENCES contact_infos (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE persons DROP CONSTRAINT contact_info__fk;

-- changeset Katarzyna.Osowska:5_MED_163_user_info_management
CREATE TABLE profile_picture_metadata
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
  user_id            BIGINT              UNIQUE               NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  file_path          VARCHAR(100),
  content_type       VARCHAR(50),

  CONSTRAINT user_photos_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE profile_picture_metadata;

-- changeset Katarzyna.Osowska:6_MED_163_user_info_management
ALTER TABLE profile_picture_metadata
  ADD CONSTRAINT user_photo_unique_user_id UNIQUE (user_id);
-- rollback ALTER TABLE profile_picture_metadata DROP CONSTRAINT user_photo_unique_user_id;

-- changeset Katarzyna.Osowska:7_MED_163_user_info_management
ALTER TABLE profile_picture_metadata
  ADD CONSTRAINT user__fk FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE profile_picture_metadata DROP CONSTRAINT user__fk;

-- changeset Anton.Dybko:1_MED_273_Home_page_referrals
CREATE TABLE referrals
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  issued_by          BIGINT                                  NOT NULL,
  specialization_id  BIGINT                                  NOT NULL,
  patient_id         BIGINT                                  NOT NULL,
  appointment_id     BIGINT,
  issue_date         DATE                                    NOT NULL,
  expiration_date    DATE                                    NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT referrals_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE referrals;

-- changeset Anton.Dybko:2_MED_273_Home_page_referrals
ALTER TABLE referrals
  ADD CONSTRAINT referrals_doctors__fk FOREIGN KEY (issued_by) REFERENCES doctors (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE referrals DROP CONSTRAINT referrals_doctors__fk;

-- changeset Anton.Dybko:3_MED_273_Home_page_referrals
ALTER TABLE referrals
  ADD CONSTRAINT referrals_patients__fk FOREIGN KEY (patient_id) REFERENCES patients (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE referrals DROP CONSTRAINT referrals_patients__fk;

-- changeset Anton.Dybko:4_MED_273_Home_page_referrals
ALTER TABLE referrals
  ADD CONSTRAINT referrals_specializations__fk FOREIGN KEY (specialization_id) REFERENCES specializations (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE referrals DROP CONSTRAINT referrals_specializations__fk;

-- changeset Anton.Dybko:5_MED_273_Home_page_referrals
ALTER TABLE referrals
  ADD CONSTRAINT referrals_consultation_appointments__fk FOREIGN KEY (appointment_id) REFERENCES consultation_appointments(id)ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE referrals DROP CONSTRAINT referrals_consultation_appointments__fk;

-- changeset Anton.Dybko:1_MED_196_Recommendations_section
CREATE TABLE recommendations
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
  service_id         BIGINT                                   NOT NULL,
  age_from           INTEGER                                   NOT NULL,
  age_to             INTEGER                                   NOT NULL,
  legal_gender       VARCHAR(10)                              NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT recommendations_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE recommendations;

-- changeset Anton.Dybko:2_MED_196_Recommendations_section
ALTER TABLE recommendations
  ADD CONSTRAINT service__fk FOREIGN KEY (service_id) REFERENCES services (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE recommendations DROP CONSTRAINT service__fk;

-- changeset Anton.Dybko:5_MED_196_Recommendations_section
ALTER TABLE recommendations
  ADD CONSTRAINT recommendations_genders__fk FOREIGN KEY (legal_gender) REFERENCES genders (gender) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE recommendations DROP CONSTRAINT recommendations_genders__fk;

-- changeset Yana.Yeustratsyeva:1_MED_269_Locations_MedicalTests
CREATE TABLE test_location
(
  test_id       BIGINT NOT NULL,
  location_id   BIGINT NOT NULL,
  CONSTRAINT test_location_pkey PRIMARY KEY (test_id, location_id)
);
-- rollback DROP TABLE test_location;

-- changeset Yana.Yeustratsyeva:2_MED_269_Locations_MedicalTests
ALTER TABLE test_location
  ADD CONSTRAINT test_location_tests_fk FOREIGN KEY (test_id) 
  REFERENCES tests (id) ON UPDATE RESTRICT ON DELETE CASCADE;
-- rollback ALTER TABLE test_location DROP CONSTRAINT test_location_tests_fk;

-- changeset Yana.Yeustratsyeva:3_MED_269_Locations_MedicalTests
ALTER TABLE test_location
  ADD CONSTRAINT test_location_locations_fk FOREIGN KEY (location_id) 
  REFERENCES locations (id) ON UPDATE RESTRICT ON DELETE CASCADE;
-- rollback ALTER TABLE test_location DROP CONSTRAINT test_location_locations_fk;
