trigger:
  none

pool:
  name: $(agent_pool_name)

parameters:
  - name: environ
    displayName: Environment
    type: string
    values:
      - prod
      - dev
    default: dev

variables:
  - group: 'medfast-global-vars'
  - name: resource_group_name  
    ${{ if eq(parameters.environ, 'dev') }}:
      value: 'medfast-rg-dev'
    ${{ if eq(parameters.environ, 'prod') }}:
      value: 'medfast-rg-prod'
  - name: tag
    value: $(Build.BuildId)

stages:

  - stage: Destroy
    jobs:
      - job: DestroyAKS
        steps:
        - task: TerraformInstaller@1
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: '1.10.0' 

        - task: TerraformTaskV4@4
          displayName: 'Terraform Init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: $(arm_service_connection)
            backendAzureRmResourceGroupName: $(resource_group_name)
            backendAzureRmStorageAccountName: $(storage_account_name)
            backendAzureRmContainerName: $(storage_container_name)
            backendAzureRmKey: $(tf_state_file)
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/tf/app-cluster'

        - task: TerraformTaskV4@4
          displayName: 'Terraform Destroy'
          inputs:
            provider: 'azurerm'
            environmentServiceNameAzureRM: $(arm_service_connection)
            command: 'destroy'
            commandOptions: '-auto-approve --var-file=$(System.DefaultWorkingDirectory)/infra/tf/dev.tfvars'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/tf/app-cluster'
