trigger:
  none

pool:
  name: $(agent_pool_name)

parameters:
  - name: environ
    displayName: Environment
    type: string
    values:
      - prod
      - dev
    default: dev

variables:
  - group: 'medfast-global-vars'
  - name: tag
    value: $(Build.BuildId)

stages:

  - stage: Destroy
    jobs:
      - job: DestroyAPP
        steps:

        - task: Bash@3
          inputs:
            targetType: 'filePath'
            filePath: '$(System.DefaultWorkingDirectory)/ci-cd/scripts/retrieve_tf_vars.sh'
            arguments: '$(tf_vars_file_name)'
            failOnStderr: true
          env:
            SYSTEM_DEFAULT_WORKINGDIRECTORY: $(System.DefaultWorkingDirectory)

        - task: TerraformInstaller@1
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: '1.10.0' 

        - task: TerraformTaskV4@4
          displayName: 'Terraform Init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: $(arm_service_connection)
            backendAzureRmResourceGroupName: $(TF_VAR_resource_group_name)
            backendAzureRmStorageAccountName: $(TF_VAR_storage_account_name)
            backendAzureRmContainerName: $(TF_VAR_storage_container_name)
            backendAzureRmKey: $(TF_VAR_tf_state_file)
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/tf/app-cluster'

        - task: TerraformTaskV4@4
          displayName: 'Terraform Destroy'
          inputs:
            provider: 'azurerm'
            environmentServiceNameAzureRM: $(arm_service_connection)
            command: 'destroy'
            commandOptions: '-auto-approve --var-file=$(System.DefaultWorkingDirectory)/$(tf_vars_file_name)'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/tf/app-cluster'
