trigger:
  branches:
    include:
      - main

pool:
  name: $(agent_pool_name)"
    demands:
    - agent.name -equals medfast-machine

variables: 
  - group: 'medfast-global-vars'

stages:
  - stage: InfrastructureSetup
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
        - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '1.10.0' 
        - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: $(service_connection)
              backendAzureRmResourceGroupName: $(resource_group_name)
              backendAzureRmStorageAccountName: $(storage_account_name)
              backendAzureRmContainerName: $(storage_container_name)
              backendAzureRmKey: $(tf_state_file)
              workingDirectory: '$(System.DefaultWorkingDirectory)/infra/tf/app-cluster'
        - task: TerraformTaskV4@4
          displayName: 'Terraform Validate'
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/tf/app-cluster'
        - task: TerraformTaskV4@4
          displayName: 'Terraform Format'
          inputs:
            provider: 'azurerm'
            command: 'fmt'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra/tf/app-cluster'
        

